targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: graphql/schema.docs.graphql
              queries_glob: graphql/queries/**.graphql
              output: lib/graphql/graphql_api.dart